#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GOH.Zastupovani.Xamarin.Resource", IsApplication=true)]

namespace GOH.Zastupovani.Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int Chybejici = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int classesSpinner = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int datesSpinner = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int hour = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int linearLayout1 = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int listView1 = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int poznamka = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int predmet = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ucebna = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int zastupujici = 2130968580;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int listview_row = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
